// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS options are not configured.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows options are not configured.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux options are not configured.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuwDApZ5tUYmEspUyRZddFIoFTvNCEK_E',
    appId: '1:470707781599:android:dbdd914e3de26762f00e6a',
    messagingSenderId: '470707781599',
    projectId: 'study-planner-with-calendar',
    storageBucket: 'study-planner-with-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuwDApZ5tUYmEspUyRZddFIoFTvNCEK_E',
    appId: '1:470707781599:ios:dbdd914e3de26762f00e6a',
    messagingSenderId: '470707781599',
    projectId: 'study-planner-with-calendar',
    storageBucket: 'study-planner-with-calendar.firebasestorage.app',
    iosBundleId: 'com.example.studyPlannerWithCalendar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwDApZ5tUYmEspUyRZddFIoFTvNCEK_E',
    appId: '1:470707781599:android:dbdd914e3de26762f00e6a',
    messagingSenderId: '470707781599',
    projectId: 'study-planner-with-calendar',
    authDomain: 'study-planner-with-calendar.firebaseapp.com',
    storageBucket: 'study-planner-with-calendar.firebasestorage.app',
  );
}
